sudo: required
dist: trusty
language: ruby
rvm:
  - 2.4.0

cache:
  bundler: true

before_install:
  - gem update --system
  - gem --version

before_script:
  - export DISPLAY=:99.0
  # - 'if ["${TRAVIS_EVENT_TYPE}" = "api"]; then export ODLAB_URL=$ODLAB_URL_API; fi'
  # - echo $TRAVIS_EVENT_TYPE $ODLAB_URL

script:
  bundle exec rspec

after_success:
  - curl -H "Content-Type: application/json" -X POST -d '{ "state":"success", "target_url":"https://travis-ci.org/devacademyla/TestTravis/builds/", "description":"The build succeeded!", "context":"Project Test" }' -u moisesnandres:b9f38f21ae4f7d95d82b68f118ab8cff2906f1d6 https://api.github.com/repos/devacademyla/testtravis/statuses/$COMMIT
#
# after_failure:
#   - curl -H "Content-Type: application/json" -X POST -d '{ "state":"failure", "target_url":"https://travis-ci.com/devacademyla/TestTravis/builds/", "description":"The build on ODLabTest failed!", "context":"continuous-integration/travis-ci/ODLabTest" }' -u username:token https://api.github.com/repos/:owner/:repo/statuses/:sha
